#!/bin/sh
## vim: set fenc=utf-8 ts=2 sw=0 sts=0 sr et si tw=0 fdm=marker fmr={{{,}}}:
##
## any2wav by Andy3153
## created   29/12/24 ~ 16:45:40
##

# {{{ Check if argument was given
origfolder=$(readlink -f "${1}" 2> /dev/null)

if [ ! -d "${origfolder}" ]; then
  echo "Not a folder."
  exit
fi
# }}}

# {{{ Create copy of files
workfolder="${origfolder}_wav"
cp -r "${origfolder}" "${workfolder}"
# }}}

# {{{ Run the conversion
find "${workfolder}" -type f -exec sh -c \
  'file="{}" &&\
  file_noext=$(echo "${file}" | sed -e "s/\.[^.]*$//")
  mv "${file}" "${file_noext}" &&\
  ffmpeg -i "${file_noext}" "${file_noext}.wav" &&\
  rm "${file_noext}"' \;
# }}}
